# Generated by Django 5.2 on 2025-06-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('plataforma_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plataforma', to='Plataforma.plataforma')),
            ],
        ),
    ]
